version: "3.8"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  app:
    image: socialapp
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
